export interface PromptTemplate { id: string; category: string; title: string; description: string; systemPrompt: string; userPrompt: string; variables: Array<{ name: string; label: string; defaultValue?: string; required?: boolean; type?: 'text' | 'number' | 'date' }>; recommendedMaxTokens: number; recommendedTemperature: number; tags?: string[] }

export const PROMPT_TEMPLATES: PromptTemplate[] = [
  { id: 'contrat_cdi_resume', category: 'contrats', title: 'Résumé contrat CDI', description: 'Génère un résumé de contrat CDI', systemPrompt: 'Tu es un assistant juridique RH.', userPrompt: 'Résume ce contrat CDI : Poste {{poste}}, Salaire {{salaire}} GNF, Date {{date_embauche}}, Période essai {{periode_essai}}, Lieu {{lieu}}.', variables: [{ name: 'poste', label: 'Poste', required: true, defaultValue: 'Développeur' }, { name: 'salaire', label: 'Salaire (GNF)', type: 'number', required: true, defaultValue: '1500000' }, { name: 'date_embauche', label: 'Date embauche', type: 'date', required: true }, { name: 'periode_essai', label: 'Période essai', defaultValue: '3 mois' }, { name: 'lieu', label: 'Lieu', defaultValue: 'Conakry' }], recommendedMaxTokens: 300, recommendedTemperature: 0.5 },
  { id: 'synthese_evaluation', category: 'evaluations', title: 'Synthèse évaluation', description: 'Synthétise une évaluation annuelle', systemPrompt: 'Tu es un coach RH.', userPrompt: 'Synthèse évaluation pour {{employe}}, poste {{poste}}, note {{note}}/5. Points forts : {{points_forts}}. Axes : {{axes_amelioration}}.', variables: [{ name: 'employe', label: 'Nom', required: true }, { name: 'poste', label: 'Poste', required: true }, { name: 'note', label: 'Note /5', type: 'number', required: true, defaultValue: '3' }, { name: 'points_forts', label: 'Points forts', required: true, defaultValue: 'Autonomie' }, { name: 'axes_amelioration', label: 'Axes amélioration', required: true, defaultValue: 'Communication' }], recommendedMaxTokens: 800, recommendedTemperature: 0.7 },
  { id: 'annonce_promotion', category: 'communication', title: 'Annonce de promotion', description: 'Annonce de promotion par email', systemPrompt: 'Tu es un communicant RH.', userPrompt: 'Rédige une annonce de promotion pour {{employe}}, ancien poste {{ancien_poste}}, nouveau poste {{nouveau_poste}}, date {{date_effet}}, réalisations {{realisations}}.', variables: [{ name: 'employe', label: 'Nom', required: true }, { name: 'ancien_poste', label: 'Ancien poste', required: true }, { name: 'nouveau_poste', label: 'Nouveau poste', required: true }, { name: 'date_effet', label: 'Date effet', type: 'date', required: true }, { name: 'realisations', label: 'Réalisations', defaultValue: 'Projets réussis' }], recommendedMaxTokens: 400, recommendedTemperature: 0.8 },
  { id: 'analyse_turnover', category: 'analyse', title: 'Analyse turnover', description: 'Analyse les causes de turnover', systemPrompt: 'Tu es un analyste RH.', userPrompt: 'Analyse le turnover pour {{equipe}} sur {{periode}}. Effectif initial {{effectif_initial}}, départs {{departs}}, taux {{taux}}%. Causes : {{causes}}.', variables: [{ name: 'equipe', label: 'Équipe', required: true, defaultValue: 'Tech' }, { name: 'periode', label: 'Période', required: true, defaultValue: '2025' }, { name: 'effectif_initial', label: 'Effectif initial', type: 'number', defaultValue: '15' }, { name: 'departs', label: 'Départs', type: 'number', defaultValue: '6' }, { name: 'taux', label: 'Taux %', type: 'number', defaultValue: '40' }, { name: 'causes', label: 'Causes', defaultValue: 'Salaire, management' }], recommendedMaxTokens: 1200, recommendedTemperature: 0.6 },
  { id: 'plan_onboarding', category: 'onboarding', title: 'Plan d\'onboarding', description: 'Plan d\'onboarding personnalisé', systemPrompt: 'Tu es un expert en onboarding.', userPrompt: 'Crée un plan d\'onboarding pour {{employe}}, poste {{poste}}, date {{date_demarrage}}, manager {{manager}}, équipe {{equipe}}.', variables: [{ name: 'employe', label: 'Nom', required: true }, { name: 'poste', label: 'Poste', required: true }, { name: 'date_demarrage', label: 'Date', type: 'date', required: true }, { name: 'manager', label: 'Manager', required: true }, { name: 'equipe', label: 'Équipe', defaultValue: 'Tech' }], recommendedMaxTokens: 1500, recommendedTemperature: 0.7 },
]

export const TEMPLATE_CATEGORIES = [
  { id: 'contrats', label: 'Contrats' }, { id: 'evaluations', label: 'Évaluations' }, { id: 'communication', label: 'Communication' }, { id: 'analyse', label: 'Analyse' }, { id: 'onboarding', label: 'Onboarding' },
]

export function getTemplateById(id: string) { return PROMPT_TEMPLATES.find(t => t.id === id) }
export function fillTemplate(template: string, values: Record<string, string>): string { return template.replace(/\{\{(\w+)\}\}/g, (_, v) => values[v] ?? `{{${v}}}`) }
